project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll
    - R-lecture-01-repl.pdf
    - R-lecture-01-repl.pptx
    - logo.png
  render:
    - index.qmd
    - installation.qmd
    - practices/01-rstudio-project/rstudio-lecture.qmd

website:
  title: "Язык R"
  site-url: "https://r-lang-vladissta.github.io/r-course/"
  navbar:
    left:
      - href: index.qmd
        text: Главная
  open-graph: true

format:
  html:
    lang: ru
    theme: readable
    css: styles.css
    toc: false

editor: visual
