project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll
    - R-lecture-01-repl.pdf
    - R-lecture-01-repl.pptx
  render:
    - index.qmd
    - installation.qmd

website:
  title: "Язык R"
  site-url: "https://r-lang-vladissta.github.io/r-course/"
  navbar: false
  open-graph: true

format:
  html:
    lang: ru
    theme: readable
    css: styles.css
    toc: false

editor: visual
